
import java.sql.Connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SANJANA
 */
import java.sql.Connection;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
public class Registration extends javax.swing.JFrame {
PreparedStatement pst = null;
    ResultSet rs = null;
    Connection conn = null;
    /**
     * Creates new form Registration
     */
    public Registration() {
        
        initComponents();
        
        Connection conn = connect();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Bcancel = new javax.swing.JButton();
        Bsubmit = new javax.swing.JButton();
        T1st = new javax.swing.JTextField();
        Tlast = new javax.swing.JTextField();
        Tphone = new javax.swing.JTextField();
        Temail = new javax.swing.JTextField();
        T2username = new javax.swing.JTextField();
        T2password = new javax.swing.JPasswordField();
        T2repass = new javax.swing.JPasswordField();
        Title = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Registration");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(69, 13, 251, 46);

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 80, 120, 43);

        jLabel3.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Phone Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(69, 178, 182, 39);

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(69, 127, 182, 44);

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(69, 224, 182, 38);

        jLabel6.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Username");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(69, 275, 182, 37);

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(69, 325, 182, 30);

        jLabel8.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Confirm Password ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(69, 368, 182, 36);

        Bcancel.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        Bcancel.setText("BACK");
        Bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcancelActionPerformed(evt);
            }
        });
        jPanel1.add(Bcancel);
        Bcancel.setBounds(301, 434, 75, 27);

        Bsubmit.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        Bsubmit.setText("SUBMIT");
        Bsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Bsubmit);
        Bsubmit.setBounds(475, 434, 95, 27);

        T1st.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        T1st.setText("Enter your first name");
        T1st.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(T1st);
        T1st.setBounds(300, 80, 270, 30);

        Tlast.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tlast.setText("Enter your last name");
        Tlast.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Tlast);
        Tlast.setBounds(301, 127, 269, 30);

        Tphone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tphone.setText("Ex: 077_________");
        Tphone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Tphone);
        Tphone.setBounds(301, 172, 269, 30);

        Temail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Temail.setText("Enter your email");
        Temail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Temail);
        Temail.setBounds(301, 224, 269, 30);

        T2username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        T2username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(T2username);
        T2username.setBounds(301, 269, 269, 30);

        T2password.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        T2password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(T2password);
        T2password.setBounds(300, 322, 270, 30);

        T2repass.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        T2repass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(T2repass);
        T2repass.setBounds(300, 370, 270, 30);

        Title.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(102, 0, 102));
        Title.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr", "Ms", "Miss" }));
        jPanel1.add(Title);
        Title.setBounds(200, 80, 84, 30);

        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sdregister.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153), 2));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-2, 0, 600, 510);

        jPanel2.setBackground(new java.awt.Color(255, 186, 235));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153), 2));
        jPanel2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("Trip to a");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(50, 70, 160, 60);

        jLabel13.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 51));
        jLabel13.setText("Life's a Sweet");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 20, 210, 60);

        jLabel12.setFont(new java.awt.Font("Snap ITC", 1, 28)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText("Candy Shop");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 130, 240, 60);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/giphy.gif"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(-120, 0, 570, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsubmitActionPerformed
        
      Connection conn = connect();
      String fname = T1st.getText();
      String lname = Tlast.getText();
      String phone = Tphone.getText();
      String email = Temail.getText();
      String username = T2username.getText();
      String password = String.valueOf(T2password.getPassword());
      String repass = String.valueOf(T2repass.getPassword());
      
        String sql = "INSERT into Registration (CustomerID,Title,FirstName,LastName,PhoneNum,Email,Username,Password) VALUES (?,?,?,?,?,?,?,?)";
        if(username.equals("")){
               JOptionPane.showMessageDialog(null, "Add a Username");
           }
        else if(password.equals("")){
            JOptionPane.showMessageDialog(null, "Add a Password");
        }
        else if(!password.equals(repass)){
            JOptionPane.showMessageDialog(null, "Password is incorrect, Re enter your password ");
        }
        else{
        try {
           pst = conn.prepareStatement(sql);
            pst.setString(2, Title.getSelectedItem().toString());
            pst.setString(3, fname);
            pst.setString(4, lname);
            pst.setString(5, phone);
            pst.setString(6, email);
           //pst.setString(5, Temail.getText());
           pst.setString(7,username);
           pst.setString(8, password);
           
           
           
            pst.execute();
            JOptionPane.showMessageDialog(null, "Registration Successful. Please login to place your order");
            Login lgf = new Login();
        lgf.setVisible(true);
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); 
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        } 
    }//GEN-LAST:event_BsubmitActionPerformed
    }
    private void BcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcancelActionPerformed
Login lgf = new Login();
        lgf.setVisible(true);
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BcancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
        
    }
    public static Connection connect() {
        Connection conn = null;

        try {

            String url = "jdbc:sqlite:/E:/DataBase/FinalProject.db";
            conn = DriverManager.getConnection(url);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }

        return conn;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcancel;
    private javax.swing.JButton Bsubmit;
    private javax.swing.JTextField T1st;
    private javax.swing.JPasswordField T2password;
    private javax.swing.JPasswordField T2repass;
    private javax.swing.JTextField T2username;
    private javax.swing.JTextField Temail;
    private javax.swing.JComboBox<String> Title;
    private javax.swing.JTextField Tlast;
    private javax.swing.JTextField Tphone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
